### PR TITLE
use refresh versions to manage dependencies

### PR DESCRIPTION
**Pull request by thebino**
Closes # 

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Comment by LouisCAD** [comment]
Hi, you probably want to use version 0.40.2 of refreshVersions, or better yet, version 0.50.1 when it's released tomorrow night.

**Comment by thebino** [comment]
> Hi, you probably want to use version 0.40.2 of refreshVersions, or better yet, version 0.50.1 when it's released tomorrow night.

Done

**Comment by LouisCAD** [comment]
You can upgrade to refreshVersions 0.50.1, and look at the changelog of 0.50.0 to see how to deal with Compose compiler version 😉

**Comment by thebino** [comment]
> You can upgrade to refreshVersions 0.50.1, and look at the changelog of 0.50.0 to see how to deal with Compose compiler version 😉

Done and adapted the compose compiler version like mentioned. Thanks for pointing out

**Pull request merged**
